pipeline {
    agent any
    stages {
        stage('IP Address') {
            steps {
                sh 'hostname -i'
                
            }
        }
        stage('disk utilization') {
            steps {
                sh 'df -kh'
                
            }
            
        }
        stage('cpu utilization') {
            steps {
                sh 'hostname'
                
            }
        }
    }
}
