pipeline{
    agent any

    stages{
        stage('Hello'){
            steps{
                sh'''
                    echo "First stage"
                '''
            }
        }

        stage('Middle-stage'){
            steps{
                sh'''
                    echo "middle stage"
                '''
            }
        }

        stage('Final-Stage'){
            steps{
                sh'''
                    echo "Final stage"
                '''
            }
        }

        stgae('Docker build'){
            sh'''
                echo "this is just test"
            '''
        }
        
    }
}