pipeline{
    agent any 

    stages{
        stage('GIT-CHECKOUT'){
            steps{
                git url: 'https://github.com/Gotoman12/MicroDegree_DevOps-06102025-M-Batch.git', branch: 'jenkins'
            }
        }
    }
}
