pipeline{
    agent any
     parameters {
        string(name: 'ENV', defaultValue: 'Prod', description: 'This is to test...')
    }
    stages{
        stage("Build stage"){
            stages{
                stage("checking code"){
                    steps{
                              sh '''
                                echo "Hello World"
                                 '''
            }
                }
                stage("testing code"){
                    steps{
                              sh '''
                                echo "Hello World"
                                 '''
            }
                }

            }
            
        }
        stage("deploying another env"){
            stages{
                stage("deploy in dev"){
                    steps{
                              sh '''
                                echo "Hello World"
                                 '''
                         }
                stage("deploy in test")
                {
                    steps{
                              sh '''
                                echo "Hello World"
                                 '''
                         }
                }
                }
            }
            
        }
    }
}