pipeline{
    agent any
    parameters{
        string (name:'ENV', defaultvalue:"Prod", description:"this is to test")
    }
    stages{
        stage("Build stage"){
            steps{
                sh '''
                    echo "this is parameter"
                    '''
            }
        }
    }
}