pipeline {
    agent none
    stages {
        stage('Run Tests') {
            parallel {
                stage('Test On Windows') {
                    agent any
                    steps {
                        echo "test"
                    }
                    
                }
                stage('Test On Linux') {
                    agent any
                    steps {
                        echo "test-2"
                    }
                    
                }
            }
        }
    }
}