pipeline {
    agent any 

    parameters {
        string(name: 'ENV', defaultValue: 'Prod', description: 'This is to test...')
    }

    stages {
        stage('Build-Stage') {
            stages {
                stage('checking_code') {
                    steps {
                        sh 'echo "Hello World"'
                    }
                }
                stage('testing_code') {
                    steps {
                        sh 'echo "Hello World"'
                    }
                }
            }
        }

        stage('Deploying to one more env') {
            stages {
                stage('deploy_to_dev') {
                    steps {
                        sh 'echo "testing in dev"'
                    }
                }
            }
        }
    }
}
